### ISSUE TITLE
Should coc-helper be a dependency not a devDependency?

### ISSUE THREAD

**Issue by Freed-Wu** [weirongxu/coc-webview#6]
Should coc-helper be a dependency not a devDependency?

<https://github.com/weirongxu/coc-webview/blob/main/package.json#L42>

```
node_modules/coc-webview/lib/server.d.ts:1:36 - error TS2307: Cannot find module 'coc-helper' or its corresponding type declarations.

1 import { HelperEventEmitter } from 'coc-helper';
```

Same as `socket.io`.

```
node_modules/coc-webview/lib/server.d.ts:3:24 - error TS2307: Cannot find module 'socket.io' or its corresponding type declarations.

3 import { Socket } from 'socket.io';
                         ~~~~~~~~~~~
```

**Comment by weirongxu** [comment]
It should be unnecessary, because the js in the lib folder will be bundled by `esbuild`, so adding socket.io and coc-helper to the dependencies will increase the download file size.

**Comment by Freed-Wu** [comment]
Oh, I see. If we `yarn add -D coc-webview`, we also need `yarn add -D socket.io coc-helper`.

**Comment by Freed-Wu** [comment]
> We also need

Maybe it should be added to README.md to let other ones know?

**Comment by weirongxu** [comment]
> Oh, I see. If we `yarn add -D coc-webview`, we also need `yarn add -D socket.io coc-helper`.

Why do we need `yarn add -D socket.io coc-helper`?

Because users will install `coc-webview` through `:CocInstall coc-webview`, socket.io and coc-helper are already included in the bundled code.

And when we want to use the `coc-webview` API in other extensions, we only need to use the two TS types (`WebviewAPI` and `WebviewPanel`, for better type hinting and completion). We call the API of `coc-webview` through coc's extension API.

**Comment by Freed-Wu** [comment]
> Why do we need yarn add -D socket.io coc-helper

Because tsc will return error :cry:

```
node_modules/coc-webview/lib/server.d.ts:1:36 - error TS2307: Cannot find module 'coc-helper' or its corresponding type declarations.

1 import { HelperEventEmitter } from 'coc-helper';
```
